<a href="/order.php">order.php</a>
<br />
<a href="/about.php">about.php</a>
<br />
<a href="/add-product.php">add-product.php</a>
<br />
<a href="/Register.php">Register.php</a>
<br />
<a href="/cart.php">cart.php</a>
<br />
<a href="/product-single.php">product-single.php</a>
<br />
<a href="/shop-sidebar.php">shop-sidebar.php</a>
<br />
<a href="/add-employee.php">add-employee.php</a>
<br />
<a href="/add-coupon.php">add-coupon.php</a>
<br />
<a href="/coupon-list.php">coupon-list.php</a>
